name: adam_asmaca
description: "Flutter ile tasarlanmış Türkçe Adam Asmaca oyunu."
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/hangman_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
